server:
  port: 8080
my:
  secret: ${random.value}
  bignumber: ${random.long}
  uuid: ${random.uuid}
  number: ${random.int}
  numbers:
    less:
      than:
        ten: ${random.int[30,50)}
    in:
      range: ${random.int(10)}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123
    initial-size: 1
    min-idle: 1
    max-idle: 10
    max-active: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
#    validation-query: SELECT 1
#    test-on-borrow: true
  rabbitmq:
    host: 47.97.100.29
    port: 5672
    username: weisihua
    password: weisihua


